server:
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001

viewRendererConfiguration:
   .ftl:
      strict_syntax: yes
      whitespace_stripping: yes

database:
  url: 'jdbc:mysql://localhost/team2'
  user: 'Team2User'
  password: 'Team2Password'
